### ISSUE TITLE
online version is dead 

### ISSUE THREAD

**Issue by mloiz** [okfn/datapipes#124]
The website where we can try the application is dead :/
http://datapipes.okfnlabs.org/

**Comment by andylolz** [comment]
Yes, it’s true 😞 

/cc @rufuspollock – I guess this is the problem:

> [Action Required] - You have used all of your Free Dyno hours
> You have used all of your 1050 Free Dyno hours for January 2018.
> 
> One or more of your Free Dyno apps are becoming more popular. Upgrade your app to Hobby dynos for $7 per dyno per month so it never sleeps and users can access it 24/7.

**Comment by pwalsh** [comment]
This probably was the problem.

@vitorbaptista can you move it to a paid dyno please, and then close this issue.
