### ISSUE TITLE
HTTPS support

### ISSUE THREAD

**Issue by fgregg** [okfn/datapipes#127]
Thanks for a great resource!

I recently updated my [website to support https](https://bunkum.us/svo/fatty_acid.html). Unfortunately, the embedded datapipes no longer show up because it is http only

http://datapipes.okfnlabs.org/csv/html/?url=https://bunkum.us/svo/data/fuel_properties.csv

works, but cannot be embedded in my https site

https://datapipes.okfnlabs.org/csv/html/?url=https://bunkum.us/svo/data/fuel_properties.csv

causes an insecure connection error in my browser (Firefox 59)

Would you be able to provide https support?

**Comment by andylolz** [comment]
Very good point – thanks for raising this, @fgregg!

looks like https://okfnlabs.org supports https, so I guess we’d need a wildcard certificate for the domain. I’ve opened a ticket for that: okfn/okfn.github.com#521

**Comment by andylolz** [comment]
Hmm – it’s failing…

```
$ heroku certs:auto
=== Automatic Certificate Management is enabled on datapipes

Domain                  Status
──────────────────────  ───────
datapipes.okfnlabs.org  Failing

=== Some domains are failing validation, please verify that your DNS matches: heroku domains

$ heroku domains
=== datapipes Heroku Domain
datapipes.herokuapp.com

=== datapipes Custom Domains
Domain Name             DNS Record Type  DNS Target
──────────────────────  ───────────────  ────────────────────────────────────
datapipes.okfnlabs.org  CNAME            datapipes.okfnlabs.org.herokudns.com
```

@rufuspollock are you able to check the DNS record on okfnlab.org matches the one above? I’ll ask on okfn/chat gitter too, in case it’s someone else with this power!

**Comment by andylolz** [comment]
Hmm… While it still says failing:

```
$ heroku certs:auto
=== Automatic Certificate Management is enabled on datapipes

Domain                  Status
──────────────────────  ───────
datapipes.okfnlabs.org  Failing
```

…https does now seem to be working:
https://datapipes.okfnlabs.org

Does this appear fixed to you, @fgregg?

**Comment by fgregg** [comment]
it does!

**Comment by andylolz** [comment]
Possibly @rufuspollock or @vitorbaptista fixed it?!

In any case, closing this, as it looks to be fixed.
